# Generated by Django 2.2.18 on 2023-03-07 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20230306_1720'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_name', models.UUIDField()),
                ('web_name', models.CharField(max_length=255)),
                ('web_address', models.CharField(max_length=255)),
                ('web_password', models.CharField(max_length=255)),
                ('created_user', models.CharField(max_length=255)),
            ],
        ),
    ]
