# Generated by Django 2.2.18 on 2023-03-07 07:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_passwordmanager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordmanager',
            name='created_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
