# Generated by Django 2.2.18 on 2023-03-07 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20230307_1252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passwordmanager',
            name='unique_name',
        ),
    ]
