# Generated by Django 2.2.18 on 2023-03-07 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_passwordmanager_unique_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordmanager',
            name='created_user',
            field=models.CharField(max_length=255),
        ),
    ]
