# Generated by Django 2.2.18 on 2023-03-07 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20230307_1259'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(max_length=255, unique=True)),
                ('created_user', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='passwordmanager',
            name='web_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
