# Generated by Django 2.2.18 on 2023-03-07 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20230307_1500'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organizationmanager',
            old_name='org_name',
            new_name='orgname',
        ),
    ]
