# Generated by Django 2.2.18 on 2023-03-08 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20230307_1555'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationMembersManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=255)),
                ('organization_id', models.CharField(max_length=255)),
                ('organization_members', models.CharField(max_length=255)),
                ('added_by', models.CharField(max_length=255)),
            ],
        ),
    ]
